apiVersion: apps/v1
kind: Deployment
metadata:
  name: pritz-hw
  labels:
    app: pritz
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pritz
  template:
    metadata:
      labels:
        app: pritz
    spec:
      containers:
      - name: pritz-hw
        image: pritz:hw
        ports:
        - containerPort: 80
